"""add user entity

Revision ID: 76a656ea64d9
Revises: 0f85a59d7f8f
Create Date: 2025-03-09 20:10:33.760526

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "76a656ea64d9"
down_revision: Union[str, None] = "0f85a59d7f8f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "usr",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("password", sa.String(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("password"),
    )
    op.create_index(op.f("ix_user_email"), "usr", ["email"], unique=True)
    op.add_column("url", sa.Column("user_id", sa.UUID(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("url", "user_id")
    op.drop_index(op.f("ix_user_email"), table_name="usr")
    op.drop_table("usr")
    # ### end Alembic commands ###
