"""remove unique on password

Revision ID: 8309b1fdf57a
Revises: 317b59d4e87c
Create Date: 2025-04-15 19:19:46.297997

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8309b1fdf57a'
down_revision: Union[str, None] = '317b59d4e87c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('usr_password_key', 'usr', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('usr_password_key', 'usr', ['password'])
    # ### end Alembic commands ###
