"""add cascade deletion

Revision ID: 498b9697ea3a
Revises: 9fa77b1457f6
Create Date: 2025-05-21 17:14:11.013564

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "498b9697ea3a"
down_revision: Union[str, None] = "9fa77b1457f6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("url_redirect_url_id_fkey", "url_redirect", type_="foreignkey")
    op.create_foreign_key(
        None, "url_redirect", "url", ["url_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "url_redirect", type_="foreignkey")
    op.create_foreign_key(
        "url_redirect_url_id_fkey", "url_redirect", "url", ["url_id"], ["id"]
    )
    # ### end Alembic commands ###
